
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

ALTER TABLE tags_translations ADD COLUMN created datetime NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE tags_translations ADD COLUMN modified datetime NOT NULL DEFAULT '0000-00-00 00:00:00';

ALTER TABLE tags ADD COLUMN poster varchar(512) NOT NULL DEFAULT '';