version: '3'
services:

  app_svanty:
    container_name: main-app
    build: ./app
    working_dir: /app
    volumes:
      - /Users/vs/Projects/svanty-monolit/uploads:/uploads
      - /Users/vs/Projects/svanty-monolit/sitemap:/sitemaps
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_HOST: host.docker.internal
      WEB_CONTEXT: "/"
      APP_UPLOADS_PATH: "/uploads"
      APP_SITEMAP_PATH: "/sitemaps"
      APP_SITE_MAP: "/sitemaps"
      APP_SHOW_SQL_IN_DEBUG: "false"
      APP_ACTIVE_PROFILE: "dev"
      APP_PORT: "8080"
    extra_hosts:
      - host.docker.internal:host-gateway
  #mysql:
  #  container_name: some-mysql
  #  image: mysql/mysql-server:5.7
  #  environment:
  #    MYSQL_ROOT_PASSWORD: toor
  #    MYSQL_DATABASE: svanty
  #    MYSQL_USER: 'svanty'
  #    MYSQL_PASSWORD: 'toor'
  #  expose:
  #    - "3306"
  #  restart: always
